name: Golang Docker Build

on:
  release:
    types:
      - released

env:
  CONTAINER_REPOSITORY: quay.io/jarno2612 # PUT YOUR OWN USERNAME HERE
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: jarno2612+almworkshop
          password: RILVTPZ4HXHF52YAB8OWN1LM3ER0M5SG8JNWO2KDLOKSTRR5GY2KI9KA77I804O2

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.CONTAINER_REPOSITORY }}/${{ env.CONTAINER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
